### ISSUE TITLE
Cannot compile on Ubuntu Linux

### ISSUE THREAD

**Issue by exebook** [cyantreeguo/Fl_Scintilla#1]
```
$ make
g++ -o editor ../../test_editor.cxx -I../../FL -I../../ -I/usr/include/freetype2 -lXft  -lfontconfig -lXinerama -lpt
hread -ldl -lm  -lX11 -lXext ../../FL/src/*.c ../../FL/src/*.cxx ../../fltk/*.cxx ../../iconv/*.c ../../lexers/*.cxx
 ../../lexlib/*.cxx ../../src/*.cxx -I../../fltk -I../../iconv -I../../include -I../../src -I../../lexers -I../../le
xlib -DSCI_LEXER -DSCI_NAMESPACE
In file included from ../../fltk/Fl_Scintilla.h:65:0,
                 from ../../test_editor.cxx:14:
../../src/ExternalLexer.h:21:30: error: expected ‘)’ before ‘*’ token
 typedef void*(EXT_LEXER_DECL *GetLexerFunction)(unsigned int Index);
                              ^
../../src/ExternalLexer.h:21:30: error: expected initializer before ‘*’ token
../../src/ExternalLexer.h:22:29: error: expected ‘)’ before ‘*’ token
 typedef int (EXT_LEXER_DECL *GetLexerCountFn)();
                             ^
../../src/ExternalLexer.h:23:30: error: expected ‘)’ before ‘*’ token
 typedef void (EXT_LEXER_DECL *GetLexerNameFn)(unsigned int Index, char *name, int buflength);
                              ^
../../src/ExternalLexer.h:24:45: error: expected ‘)’ before ‘*’ token
 typedef LexerFactoryFunction(EXT_LEXER_DECL *GetLexerFactoryFunction)(unsigned int Index);
                                             ^
../../src/ExternalLexer.h:29:2: error: ‘GetLexerFactoryFunction’ does not name a type
  GetLexerFactoryFunction fneFactory;
  ^
../../src/ExternalLexer.h:38:27: error: ‘GetLexerFactoryFunction’ has not been declared
  virtual void SetExternal(GetLexerFactoryFunction fFactory, int index);
                           ^
../../src/ExternalLexer.h: In constructor ‘Scintilla::ExternalLexerModule::ExternalLexerModule(int, Scintilla::Lexer
Function, const char*, Scintilla::LexerFunction)’:
../../src/ExternalLexer.h:35:3: error: class ‘Scintilla::ExternalLexerModule’ does not have any field named ‘fneFact
ory’
   fneFactory(0), name(languageName_){
   ^
In file included from ../../fltk/Fl_Scintilla.h:68:0,
                 from ../../test_editor.cxx:14:
../../fltk/PlatFLTK.h: In member function ‘unsigned char ICONVConverter::Open(const char*, const char*)’:
../../fltk/PlatFLTK.h:147:13: error: cast from ‘libiconv_t {aka void*}’ to ‘int’ loses precision [-fpermissive]
   if ( (int)cd > 0 ) return 1;
             ^
../../fltk/PlatFLTK.h: In member function ‘void ICONVConverter::Close()’:
../../fltk/PlatFLTK.h:157:13: error: cast from ‘libiconv_t {aka void*}’ to ‘int’ loses precision [-fpermissive]
   if ( (int)cd > 0 ) iconv_close(cd);
             ^
../../fltk/PlatFLTK.h: In member function ‘int ICONVConverter::GetLength(char*, int)’:
../../fltk/PlatFLTK.h:167:13: error: cast from ‘libiconv_t {aka void*}’ to ‘int’ loses precision [-fpermissive]
   if ( (int)cd > 0 ) {
             ^
../../fltk/PlatFLTK.h: In member function ‘int ICONVConverter::convert(char*, int, char*, int)’:
../../fltk/PlatFLTK.h:195:13: error: cast from ‘libiconv_t {aka void*}’ to ‘int’ loses precision [-fpermissive]
   if ( (int)cd > 0 ) {
             ^
```
And few more screens of errors.
I am on Ubuntu 16, got FLTK installed.

**Comment by camthesaxman** [comment]
Check out my PR #2 
I've fixed it so that it compiles and works on my Linux Mint 18.1 machine.
